// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/tonytheleg/relationship-api/internal/biz"
	"github.com/tonytheleg/relationship-api/internal/conf"
	"github.com/tonytheleg/relationship-api/internal/data"
	"github.com/tonytheleg/relationship-api/internal/server"
	"github.com/tonytheleg/relationship-api/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	relationshipRepo := data.NewRelationshipRepo(dataData, logger)
	relationshipUsecase := biz.NewRelationshipUsecase(relationshipRepo, logger)
	kesselRelationshipserviceService := service.NewKesselRelationshipserviceService(relationshipUsecase)
	grpcServer := server.NewGRPCServer(confServer, kesselRelationshipserviceService, logger)
	httpServer := server.NewHTTPServer(confServer, kesselRelationshipserviceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
