// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/tonytheleg/resource-api/internal/biz"
	"github.com/tonytheleg/resource-api/internal/conf"
	"github.com/tonytheleg/resource-api/internal/data"
	"github.com/tonytheleg/resource-api/internal/server"
	"github.com/tonytheleg/resource-api/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	resourceRepo := data.NewResourceRepo(dataData, logger)
	resourceUsecase := biz.NewResourceUsecase(resourceRepo, logger)
	kesselResourceServiceService := service.NewKesselResourceServiceService(resourceUsecase)
	grpcServer := server.NewGRPCServer(confServer, kesselResourceServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, kesselResourceServiceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
